"use client";

import { useState, useRef, useCallback, useEffect } from "react";
import {
  Mic, MicOff, FileText, Loader2, AlertTriangle, CheckCircle,
  Download, ExternalLink, Save, X, ArrowRight, Clock,
} from "lucide-react";

interface SOAPData {
  soap: { subjective: string; objective: string; assessment: string; plan: string };
  icd10Codes: Array<{ code: string; description: string; confidence: number }>;
  redFlags: string[];
  chiefComplaint: string;
  medications: Array<{ name: string; dosage: string; frequency: string }>;
}

type ScribeStep = "idle" | "recording" | "transcribing" | "analyzing" | "review" | "sending";

export default function ScribePage() {
  const [step, setStep] = useState<ScribeStep>("idle");
  const [transcript, setTranscript] = useState("");
  const [soapData, setSoapData] = useState<SOAPData | null>(null);
  const [error, setError] = useState("");
  const [showReview, setShowReview] = useState(false);
  const [recordingTime, setRecordingTime] = useState(0);
  const mediaRecorderRef = useRef<MediaRecorder | null>(null);
  const chunksRef = useRef<Blob[]>([]);
  const timerRef = useRef<NodeJS.Timeout | null>(null);

  // Recording timer
  useEffect(() => {
    if (step === "recording") {
      timerRef.current = setInterval(() => setRecordingTime(t => t + 1), 1000);
    } else {
      if (timerRef.current) clearInterval(timerRef.current);
      if (step === "idle") setRecordingTime(0);
    }
    return () => { if (timerRef.current) clearInterval(timerRef.current); };
  }, [step]);

  const formatTime = (s: number) => `${Math.floor(s / 60)}:${String(s % 60).padStart(2, "0")}`;

  const startRecording = useCallback(async () => {
    try {
      setError("");
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
      const mediaRecorder = new MediaRecorder(stream, { mimeType: "audio/webm" });
      chunksRef.current = [];

      mediaRecorder.ondataavailable = (e) => {
        if (e.data.size > 0) chunksRef.current.push(e.data);
      };

      mediaRecorder.onstop = async () => {
        stream.getTracks().forEach(t => t.stop());
        const blob = new Blob(chunksRef.current, { type: "audio/webm" });
        if (blob.size < 1000) {
          setError("Recording too short. Speak for at least a few seconds.");
          setStep("idle");
          return;
        }
        await processRecording(blob);
      };

      mediaRecorderRef.current = mediaRecorder;
      mediaRecorder.start(1000);
      setStep("recording");
    } catch {
      setError("Microphone access denied. Allow microphone in browser settings.");
    }
  }, []);

  const stopRecording = useCallback(() => {
    mediaRecorderRef.current?.stop();
  }, []);

  // Full pipeline: transcribe → analyze → show review
  const processRecording = async (blob: Blob) => {
    // Step 1: Transcribe
    setStep("transcribing");
    try {
      const formData = new FormData();
      formData.append("audio", blob, "recording.webm");
      const res = await fetch("/api/scribe/transcribe", { method: "POST", body: formData });
      const data = await res.json();
      if (!data.transcript || data.transcript === "[silence]") {
        setError("No speech detected. Try again.");
        setStep("idle");
        return;
      }
      const newTranscript = transcript ? transcript + "\n" + data.transcript : data.transcript;
      setTranscript(newTranscript);
      await analyzeSOAP(newTranscript);
    } catch {
      setError("Transcription failed. Check your connection.");
      setStep("idle");
    }
  };

  // Step 2: Analyze
  const analyzeSOAP = async (text: string) => {
    setStep("analyzing");
    try {
      const res = await fetch("/api/scribe/analyze", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ transcript: text }),
      });
      const data = await res.json();
      if (data.analysis) {
        setSoapData(data.analysis);
        setStep("review");
        setShowReview(true); // Auto-pop the review modal
      } else {
        setError("SOAP analysis failed.");
        setStep("idle");
      }
    } catch {
      setError("Analysis failed.");
      setStep("idle");
    }
  };

  // Manual analyze (for typed/pasted transcripts)
  const manualAnalyze = () => {
    if (transcript.length < 20) {
      setError("Need at least 20 characters to analyze.");
      return;
    }
    analyzeSOAP(transcript);
  };

  // Build the coding document
  const buildCodingDocument = (data: SOAPData): string => {
    const lines = [
      "CLINICAL CONSULTATION — CODING DOCUMENT",
      "=".repeat(45),
      `Date: ${new Date().toLocaleDateString("en-ZA")}`,
      `Generated by: Doctor OS AI Scribe`,
      "",
      `Chief Complaint: ${data.chiefComplaint}`,
      "",
      "DIAGNOSIS CODES (ICD-10 WHO)",
      "-".repeat(30),
      ...data.icd10Codes.map(c => `  ${c.code}  ${c.description}  [${c.confidence}%]`),
      "",
      "SUBJECTIVE",
      "-".repeat(30),
      data.soap.subjective || "—",
      "",
      "OBJECTIVE",
      "-".repeat(30),
      data.soap.objective || "—",
      "",
      "ASSESSMENT",
      "-".repeat(30),
      data.soap.assessment || "—",
      "",
      "PLAN",
      "-".repeat(30),
      data.soap.plan || "—",
    ];

    if (data.medications.length > 0) {
      lines.push("", "MEDICATIONS", "-".repeat(30));
      data.medications.forEach(m => lines.push(`  ${m.name} ${m.dosage} — ${m.frequency}`));
    }

    if (data.redFlags.length > 0) {
      lines.push("", "RED FLAGS", "-".repeat(30));
      data.redFlags.forEach(f => lines.push(`  ⚠ ${f}`));
    }

    lines.push("", "=".repeat(45), "Ready for clinical coding validation via VisioCode");
    return lines.join("\n");
  };

  const downloadDocument = () => {
    if (!soapData) return;
    const doc = buildCodingDocument(soapData);
    const blob = new Blob([doc], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `consultation-${new Date().toISOString().split("T")[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const sendToVisioCode = () => {
    if (!soapData) return;
    setStep("sending");
    // Download the document first
    downloadDocument();
    // Then open VisioCode with the data
    const codes = soapData.icd10Codes.map(c => c.code).join(", ");
    const prompt = [
      `Consultation from Doctor OS:`,
      ``,
      `Chief Complaint: ${soapData.chiefComplaint}`,
      `ICD-10 Codes: ${codes}`,
      ``,
      `Assessment: ${soapData.soap.assessment}`,
      `Plan: ${soapData.soap.plan}`,
      ``,
      `Please validate these codes, check scheme compatibility, and suggest any corrections.`,
    ].join("\n");
    window.open(`https://visiocode.vercel.app/chat?prompt=${encodeURIComponent(prompt)}`, "_blank");
    setShowReview(false);
    setStep("review");
  };

  return (
    <div className="p-4 lg:p-6 h-full flex flex-col">
      {/* Header */}
      <div className="flex items-center justify-between mb-4">
        <div>
          <h1 className="text-lg font-semibold">AI Scribe</h1>
          <p className="text-[11px] text-muted-foreground">
            {step === "idle" && "Record a consultation or paste transcript."}
            {step === "recording" && "Recording... speak naturally."}
            {step === "transcribing" && "Transcribing audio with Gemini..."}
            {step === "analyzing" && "Generating SOAP notes + ICD-10 codes..."}
            {step === "review" && "Review complete. Ready to send for coding."}
            {step === "sending" && "Sending to VisioCode..."}
          </p>
        </div>
        {/* Step indicator */}
        <div className="flex items-center gap-1.5">
          <StepDot label="Record" active={step === "recording"} done={["transcribing","analyzing","review","sending"].includes(step)} />
          <div className="w-4 h-px bg-border" />
          <StepDot label="Transcribe" active={step === "transcribing"} done={["analyzing","review","sending"].includes(step)} />
          <div className="w-4 h-px bg-border" />
          <StepDot label="SOAP" active={step === "analyzing"} done={["review","sending"].includes(step)} />
          <div className="w-4 h-px bg-border" />
          <StepDot label="Code" active={step === "review" || step === "sending"} done={step === "sending"} />
        </div>
      </div>

      {error && (
        <div className="flex items-center gap-2 px-3 py-2 rounded-md bg-[var(--color-rejected)]/10 text-[var(--color-rejected)] text-[12px] mb-3">
          <AlertTriangle className="w-3.5 h-3.5 shrink-0" /> {error}
          <button onClick={() => setError("")} className="ml-auto"><X className="w-3 h-3" /></button>
        </div>
      )}

      {/* Main Content */}
      <div className="flex-1 grid grid-cols-1 lg:grid-cols-2 gap-4 min-h-0">
        {/* Left: Recording + Transcript */}
        <div className="rounded-lg ring-1 ring-border bg-card flex flex-col overflow-hidden">
          <div className="px-4 py-2.5 border-b border-border flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Mic className="w-3.5 h-3.5 text-muted-foreground" />
              <span className="text-[13px] font-medium">Transcript</span>
            </div>
            {step === "recording" && (
              <div className="flex items-center gap-1.5">
                <div className="w-2 h-2 rounded-full bg-[var(--color-rejected)] animate-pulse" />
                <span className="text-[12px] font-mono text-[var(--color-rejected)]">{formatTime(recordingTime)}</span>
              </div>
            )}
            {(step === "transcribing" || step === "analyzing") && (
              <Loader2 className="w-3.5 h-3.5 animate-spin text-muted-foreground" />
            )}
          </div>

          <div className="flex-1 p-4 overflow-y-auto">
            {transcript ? (
              <pre className="text-[13px] whitespace-pre-wrap font-sans leading-relaxed">{transcript}</pre>
            ) : (
              <div className="flex flex-col items-center justify-center h-full text-center">
                <Mic className="w-10 h-10 text-muted-foreground/20 mb-3" />
                <p className="text-[13px] text-muted-foreground">Press the record button to start.</p>
                <p className="text-[11px] text-muted-foreground mt-1">Or type/paste a transcript below.</p>
              </div>
            )}
          </div>

          {/* Controls */}
          <div className="px-4 py-3 border-t border-border">
            <div className="flex items-center gap-3">
              <button
                onClick={step === "recording" ? stopRecording : startRecording}
                disabled={step === "transcribing" || step === "analyzing"}
                className={`w-12 h-12 rounded-full flex items-center justify-center transition-all ring-2 disabled:opacity-30 ${
                  step === "recording"
                    ? "ring-[var(--color-rejected)] bg-[var(--color-rejected)]/10 text-[var(--color-rejected)] animate-pulse"
                    : "ring-border bg-card text-foreground hover:bg-accent"
                }`}
              >
                {step === "recording" ? <MicOff className="w-5 h-5" /> : <Mic className="w-5 h-5" />}
              </button>

              <input
                type="text"
                placeholder="Type or paste transcript here, press Enter..."
                className="flex-1 ring-1 ring-border rounded-md px-3 py-2 text-[13px] bg-transparent placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring"
                disabled={step === "recording" || step === "transcribing" || step === "analyzing"}
                onKeyDown={(e) => {
                  if (e.key === "Enter" && e.currentTarget.value.trim()) {
                    setTranscript(prev => prev + (prev ? "\n" : "") + e.currentTarget.value);
                    e.currentTarget.value = "";
                  }
                }}
              />

              {transcript && step !== "recording" && step !== "transcribing" && step !== "analyzing" && !soapData && (
                <button
                  onClick={manualAnalyze}
                  className="flex items-center gap-1.5 px-3 py-2 rounded-md bg-foreground text-background text-[12px] font-medium hover:opacity-90 transition shrink-0"
                >
                  <ArrowRight className="w-3.5 h-3.5" /> Analyze
                </button>
              )}
            </div>
          </div>
        </div>

        {/* Right: SOAP Notes */}
        <div className="rounded-lg ring-1 ring-border bg-card flex flex-col overflow-hidden">
          <div className="px-4 py-2.5 border-b border-border flex items-center gap-2">
            <FileText className="w-3.5 h-3.5 text-muted-foreground" />
            <span className="text-[13px] font-medium">SOAP Notes</span>
            {soapData && <CheckCircle className="w-3 h-3 text-[var(--color-valid)] ml-auto" />}
          </div>
          <div className="flex-1 p-4 overflow-y-auto space-y-3">
            {soapData ? (
              <>
                <div className="rounded-md bg-accent px-3 py-2">
                  <span className="text-[10px] text-muted-foreground uppercase">Chief Complaint</span>
                  <p className="text-[13px] font-medium">{soapData.chiefComplaint}</p>
                </div>

                {(["subjective", "objective", "assessment", "plan"] as const).map(s => (
                  <div key={s}>
                    <label className="text-[10px] text-muted-foreground uppercase tracking-wider font-medium">
                      {s.charAt(0).toUpperCase()} — {s}
                    </label>
                    <div className="mt-1 rounded-md ring-1 ring-border bg-background p-2.5 text-[12px] leading-relaxed min-h-[32px]">
                      {soapData.soap[s] || "—"}
                    </div>
                  </div>
                ))}

                {soapData.icd10Codes.length > 0 && (
                  <div>
                    <label className="text-[10px] text-muted-foreground uppercase tracking-wider font-medium">ICD-10 Codes</label>
                    <div className="mt-1 space-y-1">
                      {soapData.icd10Codes.map((c, i) => (
                        <div key={i} className="flex items-center gap-2 rounded-md ring-1 ring-border bg-background px-2.5 py-1.5">
                          <span className="text-[12px] font-mono font-bold">{c.code}</span>
                          <span className="text-[11px] text-muted-foreground flex-1">{c.description}</span>
                          <span className="text-[10px] font-mono text-muted-foreground">{c.confidence}%</span>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {soapData.redFlags.length > 0 && (
                  <div>
                    <label className="text-[10px] text-[var(--color-rejected)] uppercase tracking-wider font-medium">Red Flags</label>
                    {soapData.redFlags.map((f, i) => (
                      <div key={i} className="flex items-center gap-1.5 text-[11px] text-[var(--color-rejected)] mt-1">
                        <AlertTriangle className="w-3 h-3 shrink-0" /> {f}
                      </div>
                    ))}
                  </div>
                )}

                {soapData.medications.length > 0 && (
                  <div>
                    <label className="text-[10px] text-muted-foreground uppercase tracking-wider font-medium">Medications</label>
                    {soapData.medications.map((m, i) => (
                      <div key={i} className="text-[11px] font-mono mt-0.5">{m.name} {m.dosage} — {m.frequency}</div>
                    ))}
                  </div>
                )}

                {/* Action bar */}
                <div className="pt-3 border-t border-border">
                  <button
                    onClick={() => setShowReview(true)}
                    className="w-full flex items-center justify-center gap-2 px-3 py-2.5 rounded-md bg-foreground text-background text-[13px] font-medium hover:opacity-90 transition"
                  >
                    <ExternalLink className="w-3.5 h-3.5" /> Review &amp; Send to VisioCode
                  </button>
                </div>
              </>
            ) : (
              <div className="flex flex-col items-center justify-center h-full text-center py-8">
                <FileText className="w-10 h-10 text-muted-foreground/20 mb-3" />
                <p className="text-[13px] text-muted-foreground">SOAP notes auto-generate after recording.</p>
                <p className="text-[11px] text-muted-foreground mt-1">Record → Transcribe → Analyze → Review → Code</p>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* ═══ REVIEW MODAL ═══ */}
      {showReview && soapData && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4">
          <div className="w-full max-w-2xl max-h-[90vh] rounded-lg ring-1 ring-border bg-card flex flex-col overflow-hidden">
            {/* Modal header */}
            <div className="px-5 py-3 border-b border-border flex items-center justify-between">
              <div>
                <h2 className="text-[15px] font-semibold">Review Before Sending</h2>
                <p className="text-[11px] text-muted-foreground">Check the coding document, then send to VisioCode for validation.</p>
              </div>
              <button onClick={() => setShowReview(false)} className="p-1 rounded hover:bg-accent transition">
                <X className="w-4 h-4 text-muted-foreground" />
              </button>
            </div>

            {/* Document preview */}
            <div className="flex-1 overflow-y-auto p-5">
              <pre className="text-[12px] font-mono whitespace-pre-wrap leading-relaxed text-muted-foreground">
                {buildCodingDocument(soapData)}
              </pre>
            </div>

            {/* Modal actions */}
            <div className="px-5 py-3 border-t border-border flex items-center gap-3">
              <button
                onClick={downloadDocument}
                className="flex items-center gap-1.5 px-3 py-2 rounded-md ring-1 ring-border text-[12px] hover:bg-accent transition"
              >
                <Download className="w-3.5 h-3.5" /> Download Only
              </button>
              <button
                onClick={() => { setShowReview(false); }}
                className="flex items-center gap-1.5 px-3 py-2 rounded-md ring-1 ring-border text-[12px] text-muted-foreground hover:bg-accent transition"
              >
                <Save className="w-3.5 h-3.5" /> Save &amp; Close
              </button>
              <div className="flex-1" />
              <button
                onClick={sendToVisioCode}
                className="flex items-center gap-2 px-4 py-2 rounded-md bg-foreground text-background text-[13px] font-medium hover:opacity-90 transition"
              >
                <ExternalLink className="w-3.5 h-3.5" /> Send to VisioCode
                <ArrowRight className="w-3.5 h-3.5" />
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

function StepDot({ label, active, done }: { label: string; active: boolean; done: boolean }) {
  return (
    <div className="flex items-center gap-1">
      <div className={`w-2 h-2 rounded-full transition-colors ${
        done ? "bg-[var(--color-valid)]" : active ? "bg-foreground animate-pulse" : "bg-border"
      }`} />
      <span className={`text-[10px] hidden sm:inline ${
        active ? "text-foreground font-medium" : done ? "text-[var(--color-valid)]" : "text-muted-foreground"
      }`}>{label}</span>
    </div>
  );
}
