"use client";

import { Download, FileSpreadsheet, FileText, Users, Receipt, CreditCard, Activity } from "lucide-react";

const EXPORT_TYPES = [
  { type: "patients", label: "Patients", icon: Users, desc: "All patient records with demographics, medical aid, contact details" },
  { type: "consultations", label: "Consultations", icon: Activity, desc: "SOAP notes, ICD-10 codes, transcripts, dates" },
  { type: "claims", label: "Claims", icon: Receipt, desc: "Claims with ICD-10, tariff codes, amounts, status" },
  { type: "invoices", label: "Invoices", icon: CreditCard, desc: "Invoices with line items, amounts, payment status" },
];

export default function ExportsPage() {
  const downloadCSV = (type: string) => {
    window.open(`/api/export/csv?type=${type}`, "_blank");
  };

  const downloadPDF = async (title: string, content: string) => {
    const res = await fetch("/api/documents/pdf", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ title, content, type: "report" }),
    });
    if (res.ok) {
      const blob = await res.blob();
      const a = document.createElement("a");
      a.href = URL.createObjectURL(blob);
      a.download = `${title.replace(/\s+/g, "_")}.pdf`;
      a.click();
    }
  };

  return (
    <div className="p-4 lg:p-6 space-y-6">
      <div>
        <h1 className="text-lg font-semibold">Exports</h1>
        <p className="text-[13px] text-muted-foreground">Download practice data as CSV or generate PDF documents.</p>
      </div>

      {/* CSV Exports */}
      <div>
        <h2 className="text-[11px] font-medium text-muted-foreground uppercase tracking-wider mb-3">Data Export (CSV)</h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          {EXPORT_TYPES.map(exp => (
            <button
              key={exp.type}
              onClick={() => downloadCSV(exp.type)}
              className="flex items-center gap-3 rounded-lg ring-1 ring-border bg-card px-4 py-3 hover:bg-accent/30 transition text-left group"
            >
              <div className="w-9 h-9 rounded-md bg-accent flex items-center justify-center">
                <exp.icon className="w-4 h-4 text-muted-foreground group-hover:text-foreground transition" />
              </div>
              <div className="flex-1 min-w-0">
                <p className="text-[13px] font-medium">{exp.label}</p>
                <p className="text-[11px] text-muted-foreground truncate">{exp.desc}</p>
              </div>
              <FileSpreadsheet className="w-4 h-4 text-muted-foreground shrink-0" />
            </button>
          ))}
        </div>
      </div>

      {/* Quick Documents */}
      <div>
        <h2 className="text-[11px] font-medium text-muted-foreground uppercase tracking-wider mb-3">Quick Documents (PDF)</h2>
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
          <button
            onClick={() => downloadPDF("Practice Report", `PRACTICE REPORT\n${"=".repeat(40)}\nDate: ${new Date().toLocaleDateString("en-ZA")}\n\nGenerated by Doctor OS\n\nThis report contains a summary of practice activity.\nFor detailed data, use the CSV exports above.`)}
            className="flex items-center gap-2 rounded-lg ring-1 ring-border bg-card px-4 py-3 hover:bg-accent/30 transition text-[12px]"
          >
            <FileText className="w-4 h-4 text-muted-foreground" /> Practice Report PDF
          </button>
          <button
            onClick={() => downloadPDF("Blank Prescription", `PRESCRIPTION\n${"=".repeat(40)}\nDate: ${new Date().toLocaleDateString("en-ZA")}\n\nPatient: ____________________\nDOB: ____________________\nMedical Aid: ____________________\n\nRp.\n\n1. ____________________\n   Sig: ____________________\n\n2. ____________________\n   Sig: ____________________\n\nDoctor: ____________________\nHPCSA: ____________________`)}
            className="flex items-center gap-2 rounded-lg ring-1 ring-border bg-card px-4 py-3 hover:bg-accent/30 transition text-[12px]"
          >
            <FileText className="w-4 h-4 text-muted-foreground" /> Blank Prescription
          </button>
          <button
            onClick={() => downloadPDF("Blank Sick Note", `MEDICAL CERTIFICATE\n${"=".repeat(40)}\nDate: ${new Date().toLocaleDateString("en-ZA")}\n\nThis is to certify that ____________________\nwas examined by me on the above date.\n\nThe patient is unfit for duties from __________ to __________.\n\nNote: Nature of illness is confidential per POPIA.\n\nDoctor: ____________________\nHPCSA: ____________________\nPractice No: ____________________\n\nSignature: ____________________`)}
            className="flex items-center gap-2 rounded-lg ring-1 ring-border bg-card px-4 py-3 hover:bg-accent/30 transition text-[12px]"
          >
            <FileText className="w-4 h-4 text-muted-foreground" /> Blank Sick Note
          </button>
        </div>
      </div>

      {/* Info */}
      <div className="rounded-lg ring-1 ring-border bg-card px-4 py-3">
        <p className="text-[11px] text-muted-foreground">
          <span className="font-medium text-foreground">Tip:</span> Use the Agent Chat for smart exports —
          &quot;Export this month&apos;s claims&quot;, &quot;Generate a prescription for Panado 500mg&quot;,
          &quot;Write a referral letter for Mrs Khumalo&quot;.
        </p>
      </div>
    </div>
  );
}
