import { FileText, Download, Mail } from "lucide-react";

export default function DocumentsPage() {
  return (
    <div className="p-6 lg:p-8">
      <h1 className="text-xl font-semibold mb-6">Documents</h1>

      <div className="grid grid-cols-2 lg:grid-cols-5 gap-3 mb-8">
        {["Prescriptions", "Referrals", "Sick Notes", "SARAA", "Clinical Notes"].map(type => (
          <div key={type} className="rounded-xl border border-white/5 bg-white/[0.02] p-4 text-center">
            <FileText className="w-5 h-5 mx-auto text-[#3DA9D1] mb-2" />
            <p className="text-xs font-medium">{type}</p>
            <p className="text-xs text-white/30 mt-1 font-mono">0</p>
          </div>
        ))}
      </div>

      <div className="rounded-xl border border-white/5 bg-white/[0.02] p-8 text-center">
        <div className="flex items-center justify-center gap-3 mb-3">
          <Download className="w-5 h-5 text-white/20" />
          <Mail className="w-5 h-5 text-white/20" />
        </div>
        <p className="text-white/30 text-sm">Documents generated by the agent will appear here.</p>
        <p className="text-white/20 text-xs mt-1">Try: &quot;Write a sick note for Sipho from today to Friday&quot;</p>
      </div>
    </div>
  );
}
